#!/bin/bash

# This file is part of the ZerusTech HTTP Cache Tutorial package.
# 
# (c) Michael Lee <michael.lee@zerustech.com>
#
# For the full copyright and license information, please view the LICENSE file 
# that was distributed with this source code.

default_base=$(dirname `cd -P $(dirname $BASH_SOURCE) && pwd`) && source $default_base/../../bootstrap.sh
runtime_base=$(dirname `cd $(dirname $BASH_SOURCE) && pwd`)

# This script accepts optional arguments for starting a php builtin server from
# command line. It is a wrapper to the php.service script.
# 
# @author Michael Lee <michael.lee@zerustech.com>

socket="0.0.0.0:8000"
doc_root=$runtime_base/web

source $app_vendor_zerustech_cli_bin/php/php-service start "$@"
