#!/bin/bash

# This file is part of the ZerusTech HTTP Cache Tutorial package.
# 
# (c) Michael Lee <michael.lee@zerustech.com>
#
# For the full copyright and license information, please view the LICENSE file 
# that was distributed with this source code.

default_base=$(dirname `cd -P $(dirname $BASH_SOURCE) && pwd`) && source $default_base/../../bootstrap.sh
runtime_base=$(dirname `cd $(dirname $BASH_SOURCE) && pwd`)

# This script accepts optional arguments for starting a varnish cache server from
# command line. It is a wrapper to the varnish-service script.
# 
# @author Michael Lee <michael.lee@zerustech.com>

config_file=$runtime_base/etc/config.vcl
key_file=$app_etc/key
http_socket="0.0.0.0:80"
varnish_socket="localhost:6082"
runtime_params="-p vcl_dir=$runtime_base/etc"

$app_vendor_zerustech_cli_bin/varnish/varnish-service -h "$varnish_home" -f "$config_file" -S "$key_file" -a "$http_socket" -T "$varnish_socket" start "$runtime_params" "$@"
